Repository SSENG-SSENG/SSENG, pull requests merged in 2025-07, with the labels that each got.

#6 ✨ Feat: 맵뷰 UI구성
  SSENG.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#9 📝 Docs: 템플릿 수정
  .github/ISSUE_TEMPLATE/add.yml
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/perf.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/remove.yml
  .github/ISSUE_TEMPLATE/style.yml
  .github/PULL_REQUEST_TEMPLATE.md
  SSENG.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 📝 Docs

#11 📦: CoreData 기능 추가 #3
  SSENG/CoreData/SSENG.xcdatamodeld/SSENG.xcdatamodel/contents
  SSENG/CoreData/data/CoreDataStack.swift
  SSENG/CoreData/data/HistoryCoreData/History+CoreDataClass.swift
  SSENG/CoreData/data/HistoryCoreData/History+CoreDataProperties.swift
  SSENG/CoreData/data/HistoryCoreData/HistoryRepository.swift
  SSENG/CoreData/data/KickboardCoreData/Kickboard+CoreDataClass.swift
  SSENG/CoreData/data/KickboardCoreData/Kickboard+CoreDataProperties.swift
  SSENG/CoreData/data/KickboardCoreData/KickboardRepository.swift
  SSENG/CoreData/data/SSENG.xcdatamodeld/.xccurrentversion
  SSENG/CoreData/data/SSENG.xcdatamodeld/SSENG.xcdatamodel/contents
  SSENG/CoreData/data/UserCoreData/User+CoreDataClass.swift
  SSENG/CoreData/data/UserCoreData/User+CoreDataProperties.swift
  SSENG/CoreData/data/UserCoreData/UserRepository.swift
Labels: 📦 Add

#15 ✨ Feat: 롱탭시 킥보드 등록 화면으로 이동하기
  SSENG/View/KickBoardView/KickBoardViewController.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#20 ✨ Feat: 등록 UI 구성
  SSENG.xcodeproj/project.pbxproj
  SSENG/Application/AppDelegate.swift
  SSENG/Application/Assets.xcassets/bike.imageset/Contents.json
  SSENG/Application/Assets.xcassets/bike.imageset/bike_crop 2.png
  SSENG/Application/Assets.xcassets/kickboard.imageset/Contents.json
  SSENG/Application/Assets.xcassets/kickboard.imageset/kickboard_crop.png
  SSENG/CoreData/data/KickboardCoreData/KickboardRepository.swift
  SSENG/View/KickBoardView/KickBoardViewController.swift
Labels: ✨ Feat

#21 ✨ Feat: MyPage 화면 TableView와 섹션별 커스텀 셀 UI 구성
  SSENG/Application/Assets.xcassets/bikePadding.imageset/Contents.json
  SSENG/Application/Assets.xcassets/bikePadding.imageset/image (2).png
  SSENG/Application/Assets.xcassets/kickboardPadding.imageset/Contents.json
  SSENG/Application/Assets.xcassets/kickboardPadding.imageset/image (1).png
  SSENG/View/MypageView/Cell/KickboardHistoryCell.swift
  SSENG/View/MypageView/Cell/KickboardRegisterCell.swift
  SSENG/View/MypageView/Cell/UserInfoCell.swift
  SSENG/View/MypageView/MypageViewcontroller.swift
Labels: ✨ Feat

#22 ✨ Feat: 킥보드 탑승 및 반납 UI 띄우기
  SSENG/Protocol/KickBoardViewControllerDelegateProtocol.swift
  SSENG/View/KickBoardView/KickBoardViewController.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#29 ✨ Feat: 등록시 마커가 화면 중앙으로 표시
  SSENG/Application/Assets.xcassets/bikeMiddle.imageset/Contents.json
  SSENG/Application/Assets.xcassets/bikeMiddle.imageset/bikeMidlde.png
  SSENG/View/KickBoardView/KickBoardViewController.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#34 ✨ Feat: 킥보드 타입별UI 및 킥보드 보기/ 보지않기 버튼
  SSENG/Model/Selected MarkerModel.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#38 Fix/code
  SSENG/CoreData/data/CoreDataStack.swift
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/MapView/MapViewController.swift
  SSENG/View/SignView/SignViewController.swift
  SSENG/View/SignView/TermsViewController.swift
Labels: 🚨 Fix

#45 ✨Feat: 마커 클릭시 위치 이동
  SSENG/View/KickBoardView/KickBoardViewController.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#52 🚨 Fix: 처음 진입할 때 바로 내 위치로 가도록 하기
  SSENG/View/KickBoardView/KickBoardViewController.swift
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/MapView/MapViewController.swift
Labels: 🚨 Fix

#60 ✨ Feat: 킥보드 대여 및 반납
  SSENG/CoreData/data/KickboardCoreData/KickboardRepository.swift
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#63 🚨 Fix: 등록 및 이용 내역 시간 포맷이 초단위로 표시되지 않는 문제 수정
  SSENG/View/MypageView/Cell/KickboardHistoryCell.swift
  SSENG/View/MypageView/Cell/KickboardRegisterCell.swift
Labels: 🚨 Fix

#64 Feat/map search
  SSENG.xcodeproj/project.pbxproj
  SSENG/Application/Info.plist
  SSENG/Model/SearchModel.swift
  SSENG/Network/SearchService.swift
  SSENG/View/MapView/MapViewController.swift
  SSENG/View/MapView/SearchResultCell.swift
Labels: ✨ Feat

#59 🎨: 회원가입 화면 및 로그인 화면 일부 리디자인
  SSENG/CoreData/data/UserCoreData/UserRepository.swift
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/LoginView/LogoTransitionAnimator.swift
  SSENG/View/SignView/SignViewController.swift
Labels: 🎨 Style

#73 🚨 Fix: 대여 데이터 수정
  SSENG/View/MapView/MapViewController.swift
Labels: 🚨 Fix

#74 자동로그인 방식 변경, 회원가입, 로그인 페이지 수정 #24, #35
  SSENG/Application/SceneDelegate.swift
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/SignView/SignViewController.swift
Labels: 🎨 Style, 🚨 Fix, ✨ Feat

#78 Fix: 로그아웃 시 자동 로그인 UserDefaults 키 삭제 추가
  SSENG/Application/SceneDelegate.swift
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/MypageView/MypageViewController.swift
  SSENG/View/SignView/SignViewController.swift
Labels: 🚨 Fix

#80 ✨ Feat: 마이페이지 이용한 킥보드 신고 기능 구현
  SSENG/View/MypageView/Cell/KickboardHistoryCell.swift
  SSENG/View/MypageView/MypageViewController.swift
Labels: ✨ Feat

#81 ✨: 주소 검색 후 마커를 찍고 지도를 탭 하면 마커가 사라지는 기능
  SSENG/View/MapView/MapViewController.swift
Labels: ✨ Feat

#87 ✨: SplashViewController 추가 및 런치 스크린 구현 #86
  SSENG/Application/SceneDelegate.swift
  SSENG/View/SplashView/SplashViewController.swift
Labels: ✨ Feat

#88 스크롤뷰 대체 #83
  SSENG/View/LoginView/LoginViewController.swift
  SSENG/View/SignView/SignViewController.swift
Labels: 🗑️ Remove, 🎨 Style, 🔨 Refactor, 📝 Docs

#97 📝: README.md 작성
  README.md
Labels: 📝 Docs

#98 📝: README.md 로고 이미지 중앙 배치
  README.md
Labels: 📝 Docs

#102 찐찐찐 최종
  README.md
Labels: 📝 Docs

#103 🚨 Fix: 잡다한 버그 수정
  SSENG/View/MapView/MapViewController.swift
Labels: 🎨 Style, 🚨 Fix, ✨ Feat
